# Generated by Django 5.2.3 on 2025-09-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_recepie_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recepie",
            name="recepie_view_count",
            field=models.IntegerField(default=1),
        ),
    ]
